// lib/constants/permissions.ts

export enum Permission {
  INVITE_USERS = "INVITE_USERS",
  MANAGE_USERS = "MANAGE_USERS",
  ASSIGN_ROLES = "ASSIGN_ROLES",
  ASSIGN_PERMISSIONS = "ASSIGN_PERMISSIONS",

  VIEW_TENANT_SETTINGS = "VIEW_TENANT_SETTINGS",
  UPDATE_TENANT_SETTINGS = "UPDATE_TENANT_SETTINGS",

  CREATE_PRODUCT = "CREATE_PRODUCT",
  VIEW_PRODUCTS = "VIEW_PRODUCTS",
  EDIT_PRODUCT = "EDIT_PRODUCT",
  ARCHIVE_PRODUCT = "ARCHIVE_PRODUCT",
  DELETE_PRODUCT = "DELETE_PRODUCT",
  DELETE_PRODUCT_PERMANENTLY = "DELETE_PRODUCT_PERMANENTLY",

  CREATE_ORDER = "CREATE_ORDER",
  VIEW_ORDERS = "VIEW_ORDERS",
  EDIT_ORDER = "EDIT_ORDER",
  CANCEL_ORDER = "CANCEL_ORDER",
  DELETE_ORDER = "DELETE_ORDER",
  DELETE_ORDER_PERMANENTLY = "DELETE_ORDER_PERMANENTLY",

  CREATE_INVOICE = "CREATE_INVOICE",
  VIEW_INVOICES = "VIEW_INVOICES",
  EDIT_INVOICE = "EDIT_INVOICE",
  DELETE_INVOICE = "DELETE_INVOICE",
  DELETE_INVOICE_PERMANENTLY = "DELETE_INVOICE_PERMANENTLY",
  RESTORE_INVOICE = "RESTORE_INVOICE",

  VIEW_PAYMENTS = "VIEW_PAYMENTS",
  REFUND_PAYMENT = "REFUND_PAYMENT",
  EXPORT_DATA = "EXPORT_DATA",
  MANAGE_BILLING = "MANAGE_BILLING",

  VIEW_AUDIT_LOGS = "VIEW_AUDIT_LOGS",
  ACCESS_BETA_FEATURES = "ACCESS_BETA_FEATURES",
  PLATFORM_ADMIN = "PLATFORM_ADMIN",

  DELETE_PERMANENTLY = "DELETE_PERMANENTLY",
  PURGE_ARCHIVED_DATA = "PURGE_ARCHIVED_DATA",
}

export enum Role {
  SUPER_ADMIN = "SUPER_ADMIN",
  SUPPORT = "SUPPORT",
  DEVELOPER = "DEVELOPER",
}

export const ALL_PERMISSIONS: string[] = Object.values(Permission);
